### ISSUE TITLE
(예시) Heading 레벨 진짜 신경 안 써도 되나요?

### ISSUE THREAD

**Issue by rohjs** [rohjs/bugless-101#1]
## Question

Heading 레벨 진짜 신경 안 써도 되나요?  
버그님께서 일단 heading 쓸 때는 레벨 같은 건 신경쓰지 말라고 하셨는데ㅠㅠ  
죄송해요 못 믿겠어요ㅠㅠㅠㅠㅠㅠㅠㅠ

## Related Contents

👉 제목과 문단 Headings & Paragraph

**Comment by rohjs** [comment]
넵 진짜 안 쓰셔도 됩니다 :)

**Comment by chajinjoo** [comment]
안녕하세요!  css랑 Javascript 강의도 오픈예정이신가요?!
너무 쏙쏙 들어오게 설명 잘해주십니다 ㅠㅠㅠ흐엉엉
