### ISSUE TITLE
<script> 질문. 

### ISSUE THREAD

**Issue by dlwlstjd89** [rohjs/bugless-101#10]
## Question

👉 이곳에 질문을 남겨주세요
<script> 를 <body> 제일 아래에 이용하는것과
<head> 태그에 쓰는것과 무슨 차이가 있나요?

어떤 분은 <head>에 쓰는걸 봐서 차이를 알고 싶습니다.
읽어주셔서 감사합니다 ^^
## Related Contents

👉 질문의 내용과 관련된 강의 제목을 알려주세요 (ex. 제목과 문단 Headings & Paragraph)

## Screenshots (optional)

👉 참고할 스크린샷이 있다면 함께 남겨주세요

**Comment by rohjs** [comment]
안녕하세요 @dlwlstjd89 님! 

HTML 태그에 직접 `script` 속성을 사용하는 것과 제일 하단에 `<script>` 태그를 사용해 자바스크립트 코드를 작성하는 것의 차이에 대해 질문하신 것 같습니다.

가령 아래와 두 코드의 차이를 물어보신 것으로 파악하였습니다.  ☺️

```html
<button type="button" onClick="alert('hi')" id="alert-button">
  경고창 버튼
</button>
```

```html
<button type="button" id="alert-button">
  경고창 버튼
</button>

<script>
  var alertButton = document.getElementById('alert-button');

  alertButton.addEventListener('click', function() {
    alert('hi');
  });
</script>
```

질문에 대한 답변을 먼저 드리자면, **일단 차이는 없습니다.**
둘다 동일하게 작동을 하니까요.

이건 마치 우리가 `<link>` 태그를 사용해서 CSS 파일을 import 할 것이냐, 아니면 각각의 HTML 태그에 `style` 속성을 사용해서 스타일을 선언해줄 것이냐의 차이와 완전히 동일합니다. 둘다 동작은 하지만, 아무래도 따로 CSS 파일을 분리해서 관리하는 게 **유지/보수** 차원에서 훨씬 좋겠죠?

자바스크립트 script도 마찬가지입니다. HTML 태그에 직접 함수를 호출하는 방식으로 사용할 수도 있지만, 서비스의 규모가 커지면 저런 식의 방식은 유지, 관리, 보수에 굉장히 어려워집니다ㅠㅠ

**요약을 하면:** 

* 작성자의 스타일의 차이이긴 하나
* `<script>`를 아래에 따로 작성하는게 유지/보수에 좋다

충분히 답변이 되었나요?
