### ISSUE TITLE
프리뷰창 어떻게 띄우신건가용

### ISSUE THREAD

**Issue by peter1201** [rohjs/bugless-101#13]
## Question

👉 이곳에 질문을 남겨주세요

2분53초대에서 프리뷰창을 띄워서 코딩한거 결과물을 보시는데 어떻게 하는지 알려주셨으면 좋겠어요 ㅠㅠ
그리구 <br>이 아니라 <br/>를 사용하시는 이유가 뭔가용? 자동완성에는 <br>로 나오는데 둘이 차이점이있나요

## Related Contents

👉 질문의 내용과 관련된 강의 제목을 알려주세요 (ex. 제목과 문단 Headings & Paragraph)

강조 Emphasis

## Screenshots (optional)

👉 참고할 스크린샷이 있다면 함께 남겨주세요
![image](https://user-images.githubusercontent.com/67989591/86867978-c52d3a80-c10e-11ea-9edb-57ed8ec8dd0f.png)

**Comment by elden0613** [comment]
Extension에 가시면 Browser Preview 라고 있어요. 그거 다운 받아서 Ctrl + Shift + P 누르시면 검색창이 뜨는데 거기서 다운받으신거 클릭하셔서 적용하시면 저렇게 뜹니당. ㅎㅎ
