### ISSUE TITLE
css랑 Javascript 강의도 나오나요?!

### ISSUE THREAD

**Issue by ghost** [rohjs/bugless-101#2]
## Question

👉 안녕하세요! css랑 Javascript 강의도 오픈예정이신가요?!
너무 쏙쏙 들어오게 설명 잘해주십니다 ㅠㅠㅠ흐엉엉

## Related Contents

👉 김버그의 버그 없는 HTML

## Screenshots (optional)

👉 참고할 스크린샷이 있다면 함께 남겨주세요

**Comment by rohjs** [comment]
안녕하세요! @chajinjoo 님 :) 
CSS 강의는 HTML 이후 업로드가 될 예정이고, JS는 아쉽지만 아직 계획은 없습니다!
CSS 강의의 경우 빠르면 한 달, 느리면 2달 후에는 오픈 가능할 것 같아요!! ㅎㅎ
더 빠르게 오픈할 수 있도록 노력하겠습니당 :)

강의 수강 중 질문 생기시면 언제든지 알려주세용! 🐝
