### ISSUE TITLE
다음 챕터

### ISSUE THREAD

**Issue by yeounseo** [rohjs/bugless-101#3]
## Question

👉 김버그님 ! 강의 잘 보고 있습니다 : ) 
     다음 챕터는 언제 쯤 연재 될까요 ?!

**Comment by rohjs** [comment]
안녕하세요! @yeounseo 님 :) 
다음 챕터는 11월 29일에 연재 예정입니다! 
좋은 강의로 찾아뵙겠습니다! 감사합니다ㅎㅎ
