### ISSUE TITLE
강의 초반인데요 HTML 태그 실습은 어떻게 하면 되나요?

### ISSUE THREAD

**Issue by boramm** [rohjs/bugless-101#4]
## Question

👉  HTML 태그 실습은 어떻게 하나요? 강의 실습을 할 수 있는 플랫폼을 알려주시면 좋을것 같아요
👉 그리고 태그 작성하실 때 "Tab" 키 처럼 안으로 들여쓰기를 하는 이유는 무엇인가요?
## Related Contents

👉강조  Emphasis

**Comment by rohjs** [comment]
안녕하세요 @boramm 답변이 늦어서 죄송합니다 :)

---

### 1. HTML 태그 실습은 어떻게 하나요? 강의 실습을 할 수 있는 플랫폼을 알려주시면 좋을것 같아요

강의 실습을 할 수 있는 플랫폼을 따로 찾아놓진 않았으나 한 가지 팁을 드리자면....!    
개인적으로는 [Behance](https://www.behance.net/)나 [Dribbble](https://dribbble.com/) 같은 디자인 사이트에 들어가서 **Free web design template**을 다운받아서 혼자서 연습을 많이 했어요.

제가 프린이 시절 연습했던 [시안](http://rohwoohyeon.com/fc-homework)을 모아둔 사이트인데 참고하시면 좋을 것 같아요. 여기 있는 디자인은 싹 다 구글링해서 무료로 다운받은 후 저 혼자서 A to Z 연습한 것이거든요!

처음 시작하실 때는 매우 막막 하실 수 있지만, 돌이켜보면 이것만큼 실력이 비약적으로 성장할 수 있는 건 없었던 것 같아요. 아직 HTML을 수강중이시니, 스타일에 대한 부담없이 연습하시기 좋을 거라 추천드립니다

👉 **포트폴리오 제작 관련 참고 영상** https://www.youtube.com/watch?v=C-aigHVu7Wg

---

### 2. 그리고 태그 작성하실 때 "Tab" 키 처럼 안으로 들여쓰기를 하는 이유는 무엇인가요?

가장 본질적인 이유는, 그래야 제가 코드를 읽기 편하기 때문이예요ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ  
이 모든 것이 저 스스로를 위해서입니다.

지금은 작성하는 코드의 분량이 적은 편이라 상관이 없겠지만, 나중에 실무에서 실제로 코딩을 하다보면 HTML만 코드가 몇 백줄은 기본, 천 줄이 넘어가기도 해요. 그럴 때 들여쓰기를 제대로 하지 않아서 뭐가 뭔지도 헷갈린다면 일의 효율성이 매우 떨어지거든요. 그래서 저는 Tab을 이용한 들여쓰기에 목숨을 겁니다!

단적인 예시를 보여드릴게요.

```html
<!-- 👍-->
<h1>
  안녕하세요
  <strong>
    어떤 말을
    <span>적어야</span>
    할 지 모르겠지만
    <a href="#">일단 열심히</a>
    적어보겠습니다
  </strong>
</h1>
``` 

```html
<!-- 👎-->
<h1>
안녕하세요<strong>
어떤 말을
<span>적어야</span>
할 지 모르겠지만<a href="#">일단 열심히</a>
적어보겠습니다
</strong>
</h1>
``` 

같은 코드이지만 딱 보시기에도 첫번째 코드가 읽기 훨씬 편하실거예요! 이런 이유로 아주 열심히 Tab 들여쓰기를 한답니다! 답변이 되었으면 좋겠네요 :)

**Comment by boramm** [comment]
안녕하세요 김버그님!

정성스러운 답변 잘 받았습니다. 

답변 참고해서 HTML 공부 끝까지 할게요 
유튜브도 정말 잘 보고 있어요.

항상감사합니다!

나의 iPad에서 보냄

2019. 12. 19. 오후 9:44, Roh Woohyeon <notifications@github.com> 작성:
