### ISSUE TITLE
html 기초 이외 나머지 강의들은 언제 오픈되나요~? 🥺

### ISSUE THREAD

**Issue by ghost** [rohjs/bugless-101#5]
## Question

👉 강의 잘보고 있습니다!
기초는 다 학습하였고,
나머지 강의 오픈을 기다리고 있습니다 ㅠㅠ
만드시느라 힘드실텐데 너무 기다려집니다!!! 귀에 쏙쏙 잘 들어오게 강의 해주시고,
넘모 이해가 잘가서 얼른 css랑 js도 빨리 하고싶어집니다!!!
감사합니다!! 화이팅팅!!  ☺️

## Related Contents

👉 html 기초 이후의 강의들

## Screenshots (optional)

👉 참고할 스크린샷이 있다면 함께 남겨주세요

**Comment by rohjs** [comment]
@chajinjoo 안녕하세요!! 강의 재밌게 수강중이시라니 너무 뿌듯합니다  
제가 서둘러서 강의 제작을 해야하는 데 작업이 자꾸 늦어져서 죄송해요 😭

최근에 업로드를 했는데, 나머지도 파이팅해서 빠르게빠르게 업로드 하도록 하겠습니다. 좀더 좋은 강의를 만드려는 욕심으로 속도가 느려지네요... 하지만 @chajinjoo 응원에 힘 입어 퐈이팅해서 제작하겠습니다!!!! 감사합니다 ❤️

PS. HTML 제작이 끝나면... 후 저는 CSS 강의도 바로 이어서 작업할 예정이예요! CSS가 레알 진짜배기니... 많은 기대해주세요! _HTML보다 더 재밌게 만드리라_
