### ISSUE TITLE
HTML훈련 Receipt 마크업 확인 부탁드립니다!

### ISSUE THREAD

**Issue by yeounseo** [rohjs/bugless-101#6]
## Bug Report

👉 .receipt 클래스 아래에 있는 span(발행일)을 수업을 따라 작성 하였을 때, css 적용시 결과물과 다르게 barcode의 하단에 위치합니다. 

## Related Contents

👉 HTML 훈련 - Receipt : 03:57 ~ 04:30에 마크업 부분 

## Screenshots (optional)

👉 참고할 스크린샷이 있다면 함께 남겨주세요
![code 스크린샷](https://user-images.githubusercontent.com/29710109/71055148-e8ef5a00-2197-11ea-9d16-9e2f19b8818a.png)
![화면 스크린샷](https://user-images.githubusercontent.com/29710109/71055149-eb51b400-2197-11ea-8e66-f127c221ac54.png)

**Comment by rohjs** [comment]
@yeounseo 안녕하세요! 코드를 확인해보니 `span`의 위치가 달라서 생기는 오류인 것 같아보입니다!

```html
<div class="receipt">
  <!-- span이 여기에 있어야 해요! -->
  <span aria-label="Issued on June 24th, 20xx">24.06.20xx</span>
  <!-- // span이 여기에 있어야 해요! -->
    <h2>
      McDonald's
    </h2>
    <strong class="barcode">
      <img src="./assets/barcode.svg" alt="Barcode" />
    </strong>
    ...
```

**마크업 상으로는 크게 문제가 되지 않지만** 제가 작성한 `styles.css`에 맞춰서 작업을 하려면 `span`을 `h2`위에 작성을 하셔야 올바르게 스타일이 적용이 될 거예요 😊

수정해보시고 다시 오류가 생기면 알려주세요!!! 화이팅!
