### ISSUE TITLE
Q, Placeholder가 적용이 안되요. & value 값이 있을 때랑 없을 때 차이를 모르겠어요.

### ISSUE THREAD

**Issue by elden0613** [rohjs/bugless-101#9]
## Question (1)

Placeholder가 적용이 안되요.

## Related Contents

 Form(input) 강의편을 보면서 따라하고 있었습니다.

 파일을 첨부할 수 있는 <input type="file"/> 을 만들었는데, 영어로만 뜨더라고요.

 그래서 내가 만약 <input type="text" , "email" or "password"/> 처럼 안에다가

 placeholder 태크를 넣는다면, 

 input type="file"도 내가 원하는 이름으로 바꿀 수 있을거라고 생각했습니다.

 그런데 적용안되길래 질문을 드립니다. 

 인풋 타입 파일은 HTML 범주안에서 한글로 수정이 불가능 한가요?

## Screenshots (optional)

👉 참고할 스크린샷이 있다면 함께 남겨주세요
![Question 1](https://user-images.githubusercontent.com/62687405/77816707-f0b88600-7118-11ea-8d1e-d9d832d3fa97.jpg)

<hr/>
<br/><br/>

## Question (2)

Value 값을 넣을 때랑 안넣을 때랑 return 값이 똑같이 돌아오는거 같은데 
그러면 value값을 따로 넣어줄 필요가 없는건가요?

## Related Contents

 From 'Form(5) - Select & Option'

 이 부분 강의를 듣고 있다가 강의가 마지막 쯤 알려주신 내용에 대해서

 스스로 작성을 하고 있었습니다.
 
 그러다가 문뜩 value 값이 없을 때, 주소값 마지막에 ' ? ' 라고 뜨셨는데(버그님 화면에서는)

 제 화면에서는 value값이 없을 때 > < 이 괄호 안에 있는 텍스트가

 리턴값으로 넘어가는거 같습니다. 

## Screenshots (optional)

👉 참고할 스크린샷이 있다면 함께 남겨주세요
![Question 2](https://user-images.githubusercontent.com/62687405/77816768-a1bf2080-7119-11ea-8919-20e75a615818.jpg)

**Comment by rohjs** [comment]
안녕하세요 @elden0613 님
질문하신 내용에 대해 답변드립니다!

#### 1. 

`<input type="file" />`의 경우에는 안타깝지만 `placeholder`가 적용되지 않습니다ㅠㅠ
No file chosen을 수정하고 싶으셨던 것 같은데, 그 부분은 아직 HTML5에서 제공을 하고 있지 않습니다.

#### 2. 

두번째 질문을 답변 드리기 위해 저도 나름대로 테스트를 해봤는데, 저또한 제 컴퓨터에서 ?로 뜨지 않고 option의 내용값, 즉 HTML이 URL에 출력이 되더라구요! 그래서 검색을 해봤는데, 원래 `<option>`에 `value` 값을 명시하지 않으면 `<option>` 안의 `textContent`가 `value`로 전송이 된다고 합니다. 하지만 올바른 HTML 작성을 위해서는 `value`를 작성해주는 것이 더 바람직하다고 하네요!

관련 참고 링크 아래에 걸어두겠습니다 :)

> Provides a value for element. If there isn't, the value of an option element is the textContent of the element.
> [https://www.w3.org/wiki/HTML/Elements/option](https://www.w3.org/wiki/HTML/Elements/option)
